# Generated by Django 4.0.4 on 2022-05-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(default='', max_length=80)),
                ('Last_name', models.CharField(default='', max_length=80)),
                ('Date', models.DateField(default=1.0)),
                ('Address', models.CharField(default='', max_length=80)),
                ('Zip_code', models.IntegerField(default=0)),
                ('Land_line', models.IntegerField(default=0)),
                ('Cellular_phone', models.IntegerField(default=0)),
                ('Infected_COVID_19', models.CharField(default='-', max_length=1)),
                ('Bowel_Disease', models.CharField(default='-', max_length=1)),
                ('Cardio_Vascular_Problems', models.CharField(default='-', max_length=1)),
                ('Depression', models.CharField(default='-', max_length=1)),
                ('Diabetes', models.CharField(default='-', max_length=1)),
                ('Hepatitis_A', models.CharField(default='-', max_length=1)),
                ('Hepatitis_B', models.CharField(default='-', max_length=1)),
                ('Hepatitis_C', models.CharField(default='-', max_length=1)),
                ('Neurological_Diseases', models.CharField(default='-', max_length=1)),
                ('Osteoporosis', models.CharField(default='-', max_length=1)),
                ('Psychotherapy', models.CharField(default='-', max_length=1)),
                ('Severe_allergy', models.CharField(default='-', max_length=1)),
                ('Stroke_CVA_of_the_Brain', models.CharField(default='-', max_length=1)),
                ('Thyroid_Problems', models.CharField(default='-', max_length=1)),
                ('tuberculosis', models.CharField(default='-', max_length=1)),
                ('other', models.CharField(default='-', max_length=100)),
            ],
        ),
    ]
