# Generated by Django 4.0.4 on 2022-05-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresult',
            name='City',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='formresult',
            name='Cellular_phone',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='formresult',
            name='Land_line',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='formresult',
            name='Zip_code',
            field=models.CharField(default='', max_length=80),
        ),
    ]
