# Generated by Django 4.0.4 on 2022-06-06 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0004_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formresult',
            name='Hepatitis_A',
        ),
        migrations.RemoveField(
            model_name='formresult',
            name='Hepatitis_B',
        ),
        migrations.RemoveField(
            model_name='formresult',
            name='Hepatitis_C',
        ),
        migrations.RemoveField(
            model_name='formresult',
            name='Neurological_Diseases',
        ),
        migrations.RemoveField(
            model_name='formresult',
            name='Osteoporosis',
        ),
        migrations.RemoveField(
            model_name='formresult',
            name='Psychotherapy',
        ),
        migrations.RemoveField(
            model_name='formresult',
            name='Severe_allergy',
        ),
        migrations.RemoveField(
            model_name='formresult',
            name='Stroke_CVA_of_the_Brain',
        ),
        migrations.RemoveField(
            model_name='formresult',
            name='Thyroid_Problems',
        ),
    ]
